---
  - name: "playbook runner"
    hosts: localhost
    connection: local 
    tasks:

    - name: var check
      ansible.builtin.import_tasks: var_check.yaml

    - name: setup disks 
      ansible.builtin.import_tasks: disks.yaml
      when: setup_disks|default(false)|bool == true

    - name: create user
      ansible.builtin.import_tasks: user.yaml

    - name: install dependencies
      ansible.builtin.import_tasks: deps.yaml

    - name: folders 
      ansible.builtin.import_tasks: dirs.yaml

    - name: swap
      ansible.builtin.import_tasks: swap.yaml

    - name: ramdisk
      ansible.builtin.import_tasks: ramdisk.yaml
      when: ramdisk_size is defined 

    - name: logrotate
      ansible.builtin.import_tasks: rotate.yaml
      
    - name: git
      ansible.builtin.import_tasks: git.yaml

    - name: solana keygen
      ansible.builtin.import_tasks: keygen.yaml

    - name: file setup
      ansible.builtin.import_tasks: file_setup.yaml

    - name: snapshot download
      ansible.builtin.import_tasks: snapshot_downloader.yaml
      when: download_snapshot|default(true)|bool == true

    - name: restart without waiting
      become: true
      become_user: root
      shell: /home/solana/restart.sh 1
      when: download_snapshot|default(true)|bool == true

    - name: restart with waiting
      become: true
      become_user: root
      shell: /home/solana/restart.sh
      when: download_snapshot|default(true)|bool == false


